### ISSUE TITLE
Missing model `enhance_LN_2019-12-18`

### ISSUE THREAD

**Issue by stweil** [DCGM/pero-enhance#31]
Running the demo from `README.md` (`python repair_page.py -i ../example/ -x ../example/ -o /path/to/outputs`) results in an error:

    FileNotFoundError: [Errno 2] No such file or directory: './model/enhance_LN_2019-12-18/repair_engine.json'

That model is not downloaded by the instructions given in `README.md`.

**Comment by halaneji** [comment]
the model is missed ...
could you please provide us the pretrained model?

**Comment by ikiss-fit** [comment]
Well, I'm NOT the author of the code or the maintainer of this repository, but I think you didn't specify the path to the JSON configuration file. I believe you need to download the OCR and enhancement models (see [section in README](https://github.com/DCGM/pero-enhance/tree/master?tab=readme-ov-file#models)) first and then run the script with the appropriate paths.
